name: d4rl-robodiff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.3  # 如果有问题，可降级到 1.19.5
  - numba=0.56.4  # 如果有问题，可降级到 0.53.1
  - scipy=1.9.1
  - gym=0.21.0
  - cffi=1.15.1
  - ipykernel=6.16
  - matplotlib=3.6.1
  - tqdm=4.64.1
  - scikit-image=0.19.3
  - pymunk=6.2.1
  - threadpoolctl=3.1.0
  - cython=0.29.32
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - psutil=5.9.2
  - llvm-openmp=14
  - pip:
    - free-mujoco-py==2.1.6
    - pygame==2.1.2
    - pybullet-svl==3.1.6.4
    - mjrl @ git+https://github.com/aravindr93/mjrl.git
    - dm-control==1.0.9
    - d4rl @ git+https://github.com/Farama-Foundation/D4RL.git