name: robodiff-d4rl
channels:
  - conda-forge
  - pytorch
  - pytorch3d
  - defaults
dependencies:
  - python=3.9.15
  - pip=22.2.2
  - cudatoolkit=11.6.2
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - torchvision=0.13.1=py39_cu116
  - pytorch3d=0.7.0=py39_cu116_pyt1121
  - numpy=1.23.3
  - pandas=2.2.3
  - scipy=1.9.1
  - scikit-image=0.19.3
  - matplotlib=3.6.1
  - h5py=3.7.0
  - opencv=4.6.0
  - pillow=9.2.0
  - tqdm=4.64.1
  - pyyaml=6.0.2
  - gym=0.21.0
  - mujoco=2.3.5
  - mujoco-py=2.1.2.14
  - dm-control=1.0.9
  - dm-env=1.6
  - dm-tree=0.1.8
  - dask-core=2023.10.1
  - cloudpickle=3.1.0
  - fsspec=2024.12.0
  - pyarrow=9.0.0
  - tensorboard=2.10.1
  - tensorboardx=2.5.1
  - setuptools=75.7.0
  - wheel=0.45.1
  - cython=0.29.32
  - numba=0.53.1
  - psutil=5.9.2
  - requests=2.32.3
  - urllib3=1.26.19
  - openssl=1.1.1w
  - libgcc-ng=14.2.0
  - libstdcxx-ng=14.2.0
  - ffmpeg=4.4.2
  - libpng=1.6.45
  - libjpeg-turbo=2.0.0
  - zlib=1.3.1
  - pip:
      - d4rl==1.1
      - robomimic==0.2.0
      - robosuite==1.2.0
      - ray==2.2.0
      - free-mujoco-py==2.1.6
      - pybullet==3.2.6
      - pygame==2.1.2
      - pymunk==6.2.1
      - wandb==0.13.3
      - einops==0.4.1
      - diffusers==0.11.1
      - accelerate==0.13.2
      - huggingface-hub==0.25.2
      - datasets==2.6.1
      - hydra-core==1.2.0
      - omegaconf==2.2.3
      - boto3==1.35.97
      - imageio-ffmpeg==0.4.7
      - nvitop==1.4.0
      - parameterized==0.9.0
      - r3m==0.0.0
      - pytorchvideo==0.1.5
      - smart-open==7.1.0
      - typeguard==4.3.0
      - virtualenv==20.28.1
      - wrapt==1.17.0