name: square_lowdim

obs_dim: 59
action_dim: 14
keypoint_dim: 3

obs_keys: &obs_keys [
  'object', 
  'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', 
  'robot1_eef_pos', 'robot1_eef_quat', 'robot1_gripper_qpos'
]
task_name: &task_name transport
dataset_type: &dataset_type ph
dataset_path: &dataset_path data/robomimic/datasets/${task.task_name}/${task.dataset_type}/low_dim.hdf5
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_datacollect_lowdim_runner.RobomimicLowdimRunner
  dataset_path: *dataset_path
  obs_keys: *obs_keys
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 5
  test_start_seed: 100000
  max_steps: 700
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  render_hw: [128,128]
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  n_envs: 28