name: real_image

image_shape: [3, 240, 320]
dataset_path: data/realrobot/expert

shape_meta: &shape_meta

  obs:
    camera_left:
      shape: ${task.image_shape}

    camera_right:
      shape: ${task.image_shape}

  action: 
    shape: [21]

dataset:
  _target_: diffusion_policy.dataset.realrobot_dataset.Hdf5RealRobotDataset
  dataset_dir: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  # n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}

