name: real_image

image_shape: [3, 1024, 1280]
dataset_path: data/realrobot/expert

shape_meta: &shape_meta

  obs:
    cam_left:
      shape: ${task.image_shape}

    # cam_right:
    #   shape: ${task.image_shape} #also need to be changed in the dataset

  action: 
    shape: [14]

dataset:
  _target_: diffusion_policy.dataset.realrobot_dataset.Hdf5RealRobotDataset
  dataset_dir: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  # n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}

